---
AWSTemplateFormatVersion: "2010-09-09"
Description: Metric filters and alarms to assist with CIS Benchmark compliance

Parameters:
  NotificationEmailAddress:
    Type: String
  CloudTrailLogGroup:
    Type: String
Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SnsTopic
      Protocol: email
      Endpoint: !Ref NotificationEmailAddress
      Region: !Ref AWS::Region

  # 3.1 Ensure a log metric filter and alarm exist for unauthorized API calls
  UnauthorizedApiCallsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '{ ($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*") }'
      LogGroupName: !Ref CloudTrailLogGroup
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: CISBenchmark
          MetricName: UnauthorizedApiCalls
  UnauthorizedApiCallsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: UnauthorizedApiCalls
      Namespace: CISBenchmark
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Threshold: 1
      Statistic: Sum
      AlarmDescription: Alarm for anuthorized API calls
      AlarmName: UnauthorizedApiCalls
      AlarmActions:
        - !Ref SnsTopic

  # 3.6 Ensure a log metric filter and alarm exist for AWS Management Console authentication failures
  ConsoleAuthFailuresMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '{ ($.eventName = ConsoleLogin) && ($.errorMessage = "Failed authentication") }'
      LogGroupName: !Ref CloudTrailLogGroup
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: CISBenchmark
          MetricName: ConsoleAuthFailures
  ConsoleAuthFailuresAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: ConsoleAuthFailures
      Namespace: CISBenchmark
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Threshold: 1
      Statistic: Sum
      AlarmDescription: Alarm for AWS console authentication failures
      AlarmName: ConsoleAuthFailures
      AlarmActions:
        - !Ref SnsTopic
